name: 'My Composite Action'
description: 'Action to run tests and some logic'

runs:
  using: "composite"
  steps:
    # Set up Python
    - name: 'Set up Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # No 'shell' here


    # Install dependencies
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
      shell: bash  # Add 'shell' property here for 'run' steps

    # Run tests (if needed)
    - name: 'Run tests'
      run: |
        pytest tests/
      shell: bash  # Use 'shell' for the 'run' command
