name: 'My Composite Action'
description: 'Action to run tests and some logic'

runs:
  using: "composite"
  steps:
  # Set up Python
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        shell: bash 

      # Install dependencies
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt
        shell: bash 
      
    
