name: 'My Composite Action'
description: 'Action to run tests and some logic'

runs:
  using: "composite"
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2
      
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash    # Specify the shell for the run step

    - name: 'Run tests'
      run: |
        pytest tests/
      shell: bash    # Ensure 'bash' is specified here as well
