name: 'Run Composite Action'

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest
   

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2  # Make sure the code is checked out first

      - name: 'Run Composite Action'
        uses: ./action.yml  # Reference your local composite action after checkout

